"""Cloudflared adapter — a NAMED Cloudflare Tunnel as a systemd --user unit.

Lifecycle host is systemd, not crr-web (spec 2026-09-02, approach A):
the unit survives crr-web restarts and reboots, and supervision stays
where the platform already does it. One-time Cloudflare account setup
(`cloudflared tunnel login` / `tunnel create` / `tunnel route dns`) is
deliberately manual — start() refuses with the exact steps rather than
driving CF auth. All subprocess wrappers are tri-state and never raise
(house adapter contract, mirrors RealTailscale).

Linux-only for now: on hosts without systemd --user this adapter reports
unavailable with an honest hint; launchd/schtasks ports follow the
existing per-OS adapter pattern later.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from crr.adapters.systemd import unit_dir
from crr.core.ports import TunnelHealth

UNIT_NAME = "crr-tunnel.service"

_NO_SYSTEMD_MSG = ("cloudflare tunnel lifecycle needs systemd --user (Linux) — "
                   "not supported on this host yet")

_SETUP_STEPS = (
    "one-time Cloudflare setup:\n"
    "  1. cloudflared tunnel login\n"
    "  2. cloudflared tunnel create <name>\n"
    "  3. cloudflared tunnel route dns <name> <hostname>\n"
    "then re-run: crr tunnel up"
)


def unit_content(cloudflared_bin: str, port: int, tunnel_name: str) -> str:
    """The crr-tunnel.service unit text. Pure so the test pins it."""
    return (
        "[Unit]\n"
        "Description=Claude-Remote-Rescue Cloudflare tunnel (generated by crr)\n"
        "After=network-online.target\n"
        "\n"
        "[Service]\n"
        f"ExecStart={cloudflared_bin} tunnel --url http://127.0.0.1:{port} "
        f"run {tunnel_name}\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


class RealCloudflared:
    def __init__(self, timeout: float, tunnel_name: str, hostname: str,
                 home: Path | None = None) -> None:
        self._timeout = timeout
        self._tunnel_name = tunnel_name
        self._hostname = hostname
        self._home = home or Path.home()

    def name(self) -> str:
        return "cloudflare"

    def available(self) -> bool:
        return shutil.which("cloudflared") is not None

    def _run(self, argv: list[str]) -> tuple[bool, str]:
        try:
            result = subprocess.run(argv, capture_output=True, text=True,
                                    timeout=self._timeout)
        except (OSError, subprocess.TimeoutExpired) as exc:
            return False, f"{argv[0]} failed: {exc}"
        if result.returncode != 0:
            return False, (result.stderr or result.stdout or "").strip() or \
                f"{' '.join(argv)} exited {result.returncode}"
        return True, (result.stdout or "").strip()

    def _unit_path(self) -> Path:
        return unit_dir(self._home) / UNIT_NAME

    def start(self, port: int) -> tuple[bool, str]:
        if shutil.which("systemctl") is None:
            return False, _NO_SYSTEMD_MSG
        cf_bin = shutil.which("cloudflared")
        if cf_bin is None:
            return False, "cloudflared binary not found on PATH — install it first"
        if not self._tunnel_name or not self._hostname:
            return False, ("cloudflare_tunnel_name and cloudflare_hostname must "
                           "be set (config.toml or dashboard settings)")
        ok, msg = self._run(["cloudflared", "tunnel", "info", self._tunnel_name])
        if not ok:
            return False, (f"tunnel {self._tunnel_name!r} not usable ({msg}) — "
                           + _SETUP_STEPS)
        unit = self._unit_path()
        unit.parent.mkdir(parents=True, exist_ok=True)
        unit.write_text(unit_content(cf_bin, port, self._tunnel_name),
                        encoding="utf-8")
        ok, msg = self._run(["systemctl", "--user", "daemon-reload"])
        if not ok:
            return False, f"daemon-reload failed: {msg}"
        ok, msg = self._run(["systemctl", "--user", "enable", "--now", UNIT_NAME])
        if not ok:
            return False, f"enable --now failed: {msg}"
        return True, f"{UNIT_NAME} enabled and started"

    def stop(self) -> tuple[bool, str]:
        if shutil.which("systemctl") is None:
            return False, _NO_SYSTEMD_MSG
        return self._run(["systemctl", "--user", "disable", "--now", UNIT_NAME])

    def health(self) -> TunnelHealth:
        try:
            result = subprocess.run(
                ["systemctl", "--user", "is-active", UNIT_NAME],
                capture_output=True, text=True, timeout=self._timeout,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            return TunnelHealth("unknown", f"systemctl unavailable: {exc}")
        state = (result.stdout or "").strip()
        if state == "active":
            return TunnelHealth("up", f"{UNIT_NAME} active")
        if state in ("inactive", "failed", "deactivating"):
            return TunnelHealth("down", f"{UNIT_NAME} {state}")
        return TunnelHealth("unknown", f"{UNIT_NAME} state {state!r}")

    def advertise_url(self) -> str | None:
        if not self._hostname:
            return None
        return f"https://{self._hostname}/"

    def setup_hint(self) -> str | None:
        return _SETUP_STEPS
