"""systemd watchdog adapter (Linux) — generates the revive timer + service.

A user timer fires ``crr revive`` on a fixed interval so revival is
autonomous. This adapter only *builds and writes* the unit files and
reports the enable/linger commands as data; running them (a real change to
the live user manager) is the composition root's job on explicit request,
never a side effect of generation or tests.

The unit environment is made self-sufficient because a user service does
NOT inherit the interactive shell's exported vars:

- ``XDG_STATE_HOME`` is baked from the resolved value, or the service would
  fall back to the default and watch the wrong (empty) state dir — silently
  reviving nothing ([lesson: interop PATH], generalized to state).
- ``PATH`` is derived from the resolved locations of the binaries
  ``crr revive`` actually calls (tmux, ps, claude) plus system dirs — not a
  blanket copy of the current $PATH, which carries venv/ephemeral entries
  absent at service runtime. A missing ``claude`` on PATH would make every
  revived session die instantly on exec.

Invoked only from crr.cli; no core port (core never spawns services).
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from crr import __version__
from crr.core.config import CONFIG_DEFAULTS_VERSION, DEFAULTS


def _stamp() -> str:
    """Version stamp for generated artifacts (audit P7): every STORED crr
    artifact carries a version so a stale shape is distinguishable later;
    generated install artifacts get the same discipline."""
    return f"# generated by crr {__version__} (config-defaults v{CONFIG_DEFAULTS_VERSION})\n"

SERVICE_NAME = "crr-revive.service"
TIMER_NAME = "crr-revive.timer"
USER_MANAGER_FALLBACK_UNIT = "crr-user-manager.service"
WEB_SERVICE_NAME = "crr-web.service"
AWAKE_SERVICE_NAME = "crr-awake.service"

# Binaries `crr revive` shells out to (directly or via the revived command).
SERVICE_BINARIES = ("tmux", "ps", "claude")

_SYSTEM_PATH_DIRS = (
    "/usr/local/sbin", "/usr/local/bin",
    "/usr/sbin", "/usr/bin", "/sbin", "/bin",
)


def resolve_service_path(
    crr_bin: str, extra_binaries: tuple[str, ...] = ()
) -> tuple[str, list[str]]:
    """Return (PATH string, list of unresolved binary names).

    Dirs are ordered: crr's own dir, then the dirs of each resolved binary
    (SERVICE_BINARIES followed by any caller-supplied ``extra_binaries``),
    then existing system dirs — deduped, order-preserving.

    ``extra_binaries`` exists for host-specific extras a caller wants baked
    in without touching SERVICE_BINARIES itself — e.g. the CLI passes
    ``("wt.exe", "wsl.exe")`` on WSL, since a service's PATH does not
    inherit the interactive shell's Windows-appended entries and the tab
    spawner shells out to them directly ([lesson: interop PATH]).
    """
    dirs: list[str] = []

    def add(d: str) -> None:
        if d and d not in dirs:
            dirs.append(d)

    add(os.path.dirname(os.path.abspath(crr_bin)))
    missing: list[str] = []
    for name in (*SERVICE_BINARIES, *extra_binaries):
        found = shutil.which(name)
        if found:
            add(os.path.dirname(os.path.abspath(found)))
        else:
            missing.append(name)
    for d in _SYSTEM_PATH_DIRS:
        if os.path.isdir(d):
            add(d)
    return ":".join(dirs), missing


def revive_service_unit(crr_bin: str, path: str, state_home: str) -> str:
    # KillMode=process is load-bearing, not a nicety: this is a Type=oneshot
    # service whose whole job is to spawn DETACHED tmux sessions and exit.
    # Under the default KillMode=control-group, systemd reaps every process in
    # the service's cgroup when the oneshot finishes — including the tmux
    # server it just started — so the revived sessions die the instant the
    # watchdog completes (a silent, total failure of revival). KillMode=process
    # kills only crr itself on stop and leaves the tmux server alone.
    # (Found on real systemd during the hardware acceptance test.)
    return (
        _stamp()
        + "[Unit]\n"
        "Description=Claude-Remote-Rescue watchdog (revive crashed claude sessions)\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        "KillMode=process\n"
        f"Environment=PATH={path}\n"
        f"Environment=XDG_STATE_HOME={state_home}\n"
        f"ExecStart={crr_bin} revive\n"
    )


def revive_timer_unit(interval_seconds: int) -> str:
    return (
        _stamp()
        + "[Unit]\n"
        "Description=Claude-Remote-Rescue watchdog timer\n"
        "\n"
        "[Timer]\n"
        f"OnBootSec={interval_seconds}s\n"
        f"OnUnitActiveSec={interval_seconds}s\n"
        "Persistent=true\n"
        "\n"
        "[Install]\n"
        "WantedBy=timers.target\n"
    )


def web_service_unit(
    crr_bin: str, path: str, state_home: str, port: int, wsl_distro: str = "",
    *, restart_seconds: int = DEFAULTS["web_restart_seconds"],
) -> str:
    """A long-running dashboard service (loopback; tailnet-served).

    Type=simple + Restart so the dashboard stays up across crashes, and
    WantedBy=default.target + linger so it survives logout and comes back
    at (re)boot — the ROADMAP's "dashboard reachable after reboot".

    ``wsl_distro``, when given, bakes ``WSL_DISTRO_NAME`` the same way
    ``XDG_STATE_HOME`` is baked above: the service does not inherit the
    interactive shell's exported vars, and cli.py's tab-spawner selection
    reads ``os.environ.get("WSL_DISTRO_NAME")`` at request time to target
    ``wsl.exe --distribution <name>`` — unbaked, a multi-distro host would
    silently open the tab in the *default* distro instead of this one.

    ``restart_seconds`` (audit P5) is the same judgment call as the watchdog
    interval — a named config default (``web_restart_seconds``), not a
    baked literal; the default here only covers callers with no Config to
    hand.
    """
    distro_line = f"Environment=WSL_DISTRO_NAME={wsl_distro}\n" if wsl_distro else ""
    return (
        _stamp()
        + "[Unit]\n"
        "Description=Claude-Remote-Rescue dashboard (loopback; tailnet-served)\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"Environment=PATH={path}\n"
        f"Environment=XDG_STATE_HOME={state_home}\n"
        f"{distro_line}"
        f"ExecStart={crr_bin} web --port {port}\n"
        "Restart=on-failure\n"
        f"RestartSec={restart_seconds}\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def awake_service_unit(
    crr_bin: str, path: str, state_home: str,
    *, restart_seconds: int = DEFAULTS["web_restart_seconds"],
) -> str:
    """The loop that holds the machine awake while a session is live.

    Its own unit rather than a job inside crr-web: the hold is a child of
    whatever process owns it, and tying that to the dashboard would couple
    "am I serving a page" to "may this machine sleep".

    No ``KillSignal=`` override — the default SIGTERM is what lets the loop
    release the hold in its ``finally`` before exiting.
    """
    return (
        _stamp()
        + "[Unit]\n"
        "Description=Claude-Remote-Rescue keep-awake\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"Environment=PATH={path}\n"
        f"Environment=XDG_STATE_HOME={state_home}\n"
        f"ExecStart={crr_bin} awake\n"
        "Restart=on-failure\n"
        f"RestartSec={restart_seconds}\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def stop_awake_command() -> list[str]:
    """Stop the keep-awake loop, which IS how the hold is released."""
    return ["systemctl", "--user", "stop", AWAKE_SERVICE_NAME]


def unit_dir(home: Path) -> Path:
    return home / ".config" / "systemd" / "user"


def write_units(target_dir: Path, units: dict[str, str]) -> list[Path]:
    """Write ``{filename: content}`` units; return their paths."""
    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for name, content in units.items():
        p = target_dir / name
        p.write_text(content, encoding="utf-8")
        paths.append(p)
    return paths


def critical_enable_commands() -> list[list[str]]:
    """The enable commands whose failure means the install genuinely failed.

    Split from linger ([Task 7], live evidence 2026-07-31): on WSL2,
    `loginctl enable-linger` reliably exits 1 (a benign dbus quirk) even
    though the services run fine — the user manager starts with the
    session regardless. Only these four (data-writing, real service
    activation) are load-bearing for "is the watchdog/dashboard/keep-awake
    running".
    """
    return [
        ["systemctl", "--user", "daemon-reload"],
        ["systemctl", "--user", "enable", "--now", TIMER_NAME],
        ["systemctl", "--user", "enable", "--now", WEB_SERVICE_NAME],
        ["systemctl", "--user", "enable", "--now", AWAKE_SERVICE_NAME],
    ]


def linger_command() -> list[str]:
    """The linger-enable command, run and judged separately from the above.

    linger lets the user manager run the timer and the dashboard without an
    active login — essential on a headless box reached only by SSH. Its
    failure is downgraded to a warning by the caller (see
    critical_enable_commands' docstring) rather than failing the install.
    """
    return ["loginctl", "enable-linger"]


def enable_commands() -> list[list[str]]:
    """The full activation sequence (data, not run) — print-mode output.

    Unchanged by the critical/linger split: still critical_enable_commands()
    plus linger, in the same order, for `crr systemd` (no --install) to
    display verbatim.
    """
    return critical_enable_commands() + [linger_command()]


def disable_commands() -> list[list[str]]:
    """The commands that deactivate the watchdog + dashboard + keep-awake
    (data, not run).

    Mirror of enable_commands; linger is left alone (other services may
    rely on it — enabling it was additive, so removal is the user's call).
    """
    return [
        ["systemctl", "--user", "disable", "--now", TIMER_NAME],
        ["systemctl", "--user", "disable", "--now", WEB_SERVICE_NAME],
        ["systemctl", "--user", "disable", "--now", AWAKE_SERVICE_NAME],
        ["systemctl", "--user", "daemon-reload"],
    ]

# --- user-manager fallback (2026-09-08: WSL logind/linger race) -----------
#
# logind is supposed to start user@<uid> at boot for lingering users and
# silently did not at the 2026-09-05 boot — three days with crr-web and the
# revive watchdog down. The fallback is a SYSTEM-level oneshot (root's
# systemd, not --user) that starts the user manager with the same ordering
# user@.service itself carries; starting an already-active unit is a no-op,
# so it never conflicts with a boot where logind behaves.
#
# Root is reached through Windows-side WSL interop (`wsl.exe -u root`),
# which WSL grants without a password — the same door `crr
# reachable-at-boot --install`'s elevated PowerShell uses on the Windows
# side. Builders are pure so tests pin the exact argv; only the cli runs
# them, inside --install's existing consent prompt.

_WSL_EXE = "/mnt/c/Windows/System32/wsl.exe"


def user_manager_fallback_unit(uid: int) -> str:
    """The crr-user-manager.service unit text for ``uid``."""
    return (
        "[Unit]\n"
        f"Description=Start user manager for UID {uid} at boot "
        "(crr linger fallback — WSL logind race, 2026-09-08)\n"
        "After=systemd-user-sessions.service systemd-logind.service\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"ExecStart=/usr/bin/systemctl start user@{uid}.service\n"
        "RemainAfterExit=yes\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def user_manager_fallback_state(timeout_seconds: float) -> str:
    """Tri-state install probe: "installed" | "missing" | "unknown".

    Querying needs no root (`systemctl is-enabled` on the SYSTEM manager).
    Only a confident "enabled" counts as installed: a present-but-disabled
    unit will not fire at boot, which is the failure this exists to stop.
    Every probe failure degrades to "unknown" (F16), never a guess.
    """
    if shutil.which("systemctl") is None:
        return "unknown"
    try:
        r = subprocess.run(
            ["systemctl", "is-enabled", USER_MANAGER_FALLBACK_UNIT],
            capture_output=True, text=True, timeout=timeout_seconds,
        )
    except (subprocess.SubprocessError, OSError):
        return "unknown"
    answer = (r.stdout or "").strip()
    if answer == "enabled":
        return "installed"
    if answer in ("not-found", "disabled", "masked", "static", ""):
        return "missing"
    return "unknown"


def user_manager_fallback_install_argv(uid: int) -> list[str]:
    """Word-form argv installing + enabling the fallback unit as root."""
    unit_path = f"/etc/systemd/system/{USER_MANAGER_FALLBACK_UNIT}"
    script = (
        f"printf '%s' {_shq(user_manager_fallback_unit(uid))} > {unit_path} "
        f"&& systemctl daemon-reload "
        f"&& systemctl enable --now {USER_MANAGER_FALLBACK_UNIT}"
    )
    return [_WSL_EXE, "-u", "root", "--", "bash", "-c", script]


def user_manager_fallback_uninstall_argv() -> list[str]:
    """Word-form argv disabling + removing the fallback unit as root."""
    unit_path = f"/etc/systemd/system/{USER_MANAGER_FALLBACK_UNIT}"
    script = (
        f"systemctl disable {USER_MANAGER_FALLBACK_UNIT}; "
        f"rm -f {unit_path} && systemctl daemon-reload"
    )
    return [_WSL_EXE, "-u", "root", "--", "bash", "-c", script]


def _shq(text: str) -> str:
    """Single-quote ``text`` for the bash -c script (no shlex import churn)."""
    return "'" + text.replace("'", "'\\''") + "'"
