import json

from crr import transcript

SID = "11111111-2222-3333-4444-555555555555"
CWD = "/home/u/my.project"


def user_line(text, **extra):
    obj = {"type": "user", "message": {"role": "user", "content": text}}
    obj.update(extra)
    return json.dumps(obj)


def tool_result_line():
    return json.dumps(
        {
            "type": "user",
            "message": {
                "role": "user",
                "content": [
                    {"type": "tool_result", "tool_use_id": "t1", "content": "ok"}
                ],
            },
        }
    )


def assistant_line(text="I did the thing"):
    return json.dumps(
        {
            "type": "assistant",
            "message": {"role": "assistant", "content": [{"type": "text", "text": text}]},
        }
    )


def make_transcript(tmp_path, lines, sid=SID, cwd=CWD):
    proj = tmp_path / "projects"
    d = proj / transcript.cwd_slug(cwd)
    d.mkdir(parents=True, exist_ok=True)
    (d / (sid + ".jsonl")).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return proj


# ---------------------------------------------------------------------------
# Slug + path safety


def test_cwd_slug_maps_non_alnum_to_dash():
    # Verified against a real ~/.claude/projects: /home/user -> -home-user
    assert transcript.cwd_slug("/home/user") == "-home-user"
    assert transcript.cwd_slug("/home/u/my.project") == "-home-u-my-project"


def test_transcript_path_rejects_non_uuid_sid(tmp_path):
    assert transcript.transcript_path("../../etc/passwd", CWD, tmp_path) is None
    assert transcript.transcript_path("not-a-uuid", CWD, tmp_path) is None
    assert transcript.transcript_path("", CWD, tmp_path) is None
    path = transcript.transcript_path(SID, CWD, tmp_path)
    assert path is not None and path.name == SID + ".jsonl"


# ---------------------------------------------------------------------------
# Genuine-prompt extraction and the skip-list


def test_returns_most_recent_genuine_prompt(tmp_path):
    proj = make_transcript(
        tmp_path,
        [user_line("older prompt"), assistant_line(), user_line("newest prompt")],
    )
    assert transcript.last_prompt(SID, CWD, proj) == "newest prompt"


def test_skips_tool_results(tmp_path):
    proj = make_transcript(
        tmp_path, [user_line("real prompt"), tool_result_line(), tool_result_line()]
    )
    assert transcript.last_prompt(SID, CWD, proj) == "real prompt"


def test_skips_command_wrapper_messages(tmp_path):
    proj = make_transcript(
        tmp_path,
        [
            user_line("real prompt"),
            user_line("<command-name>/clear</command-name>"),
            user_line("<local-command-stdout>output</local-command-stdout>"),
            user_line("Caveat: the messages below were generated by the user"),
        ],
    )
    assert transcript.last_prompt(SID, CWD, proj) == "real prompt"


def test_skips_task_notifications(tmp_path):
    proj = make_transcript(
        tmp_path,
        [user_line("real prompt"), user_line("<task-notification>\ndone\n</task-notification>")],
    )
    assert transcript.last_prompt(SID, CWD, proj) == "real prompt"


def test_skips_system_reminder_only_and_strips_embedded(tmp_path):
    proj = make_transcript(
        tmp_path,
        [
            user_line("real prompt <system-reminder>secret plumbing</system-reminder> tail"),
            user_line("<system-reminder>\nonly plumbing here\n</system-reminder>"),
        ],
    )
    got = transcript.last_prompt(SID, CWD, proj)
    assert got == "real prompt tail"
    assert "plumbing" not in got


def test_skips_compaction_continuation_summaries(tmp_path):
    proj = make_transcript(
        tmp_path,
        [
            user_line("real prompt"),
            user_line(
                "This session is being continued from a previous conversation"
                " that ran out of context. Summary follows."
            ),
            user_line("flagged summary", isCompactSummary=True),
        ],
    )
    assert transcript.last_prompt(SID, CWD, proj) == "real prompt"


def test_skips_meta_sidechain_and_non_user_roles(tmp_path):
    proj = make_transcript(
        tmp_path,
        [
            user_line("real prompt"),
            user_line("stop-hook feedback", isMeta=True),
            user_line("sidechain chatter", isSidechain=True),
            assistant_line("assistant text is never a prompt"),
            json.dumps({"type": "queue-operation", "operation": "enqueue"}),
        ],
    )
    assert transcript.last_prompt(SID, CWD, proj) == "real prompt"


def test_truncates_and_collapses_whitespace(tmp_path):
    long = ("word " * 100).strip()
    proj = make_transcript(tmp_path, [user_line("a\n\n  b\t" + long)])
    got = transcript.last_prompt(SID, CWD, proj)
    assert got is not None
    assert len(got) <= 121
    assert got.startswith("a b word")
    assert got.endswith("…")
    assert "\n" not in got


def test_missing_transcript_returns_none(tmp_path):
    assert transcript.last_prompt(SID, CWD, tmp_path / "nope") is None


def test_all_garbage_returns_none(tmp_path):
    proj = make_transcript(tmp_path, [tool_result_line(), assistant_line()])
    assert transcript.last_prompt(SID, CWD, proj) is None


# ---------------------------------------------------------------------------
# Backwards streaming


def test_backwards_streaming_multi_block_padding_prefix(tmp_path):
    """A multi-block pile of non-prompt lines before the genuine prompt:
    the extractor must find the prompt reading backwards without loading
    the file, and block-boundary line splits must reassemble correctly."""
    block = 512
    padding = [assistant_line("pad " + ("x" * 200))] * 50  # ~10KB >> several blocks
    lines = padding + [user_line("the genuine one")] + [tool_result_line()] * 3
    proj = make_transcript(tmp_path, lines)
    got = transcript.last_prompt(SID, CWD, proj, block_size=block)
    assert got == "the genuine one"


def test_line_longer_than_block_reassembled(tmp_path):
    """A single JSON line spanning many read blocks parses intact."""
    big_prompt = "start " + ("y" * 5000) + " end"
    proj = make_transcript(
        tmp_path, [user_line("older"), user_line(big_prompt), tool_result_line()]
    )
    got = transcript.last_prompt(SID, CWD, proj, block_size=256)
    assert got is not None
    assert got.startswith("start yyy")


def test_max_bytes_early_exit(tmp_path):
    """Only the file tail is scanned: a prompt buried beyond max_bytes is
    not found (the whole file is never read)."""
    lines = [user_line("buried far too deep")] + [assistant_line("z" * 300)] * 40
    proj = make_transcript(tmp_path, lines)
    got = transcript.last_prompt(SID, CWD, proj, block_size=256, max_bytes=1024)
    assert got is None
