# crr fish shim — source this from ~/.config/fish/config.fish.  Generated by
# `crr shim fish`, which bakes the absolute crr path into the set below.
# Dependency-free; safe to source even when crr is absent.

set -g _CRR_BIN "@CRR_BIN@"

# [lesson: env leakage] Scrub inherited control vars so a revived tmux
# session's environment never leaks into an ordinary shell.
for _crr_v in (set --names | string match 'CRR_CTRL_*')
    set -e $_crr_v
end

# [lesson: PATH poisoning] Absolute path only; a missing binary is a silent
# no-op, never an error line into the prompt.
function _crr
    test -x "$_CRR_BIN"; or return 0
    "$_CRR_BIN" $argv 2>/dev/null
end

function _crr_host
    if set -q TMUX
        echo -n tmux
    else if set -q SSH_TTY; or set -q SSH_CONNECTION
        echo -n ssh
    else
        echo -n tab
    end
end

# Register this shell at start.
_crr register --pid $fish_pid --cwd $PWD --shell fish --host (_crr_host) >/dev/null

# fish's native event hooks — preexec before each command, exit on teardown.
function _crr_preexec --on-event fish_preexec
    _crr last-cmd --pid $fish_pid --cmd "$argv" --cwd $PWD >/dev/null
end

function _crr_deregister --on-event fish_exit
    _crr deregister --pid $fish_pid >/dev/null
end
