# crr zsh shim — source this from ~/.zshrc.  Generated by `crr shim zsh`,
# which bakes the absolute crr path into the assignment below.
# Dependency-free; safe to source even when crr is absent.
# generated by crr @CRR_VERSION@ (config-defaults v@CRR_DEFAULTS_V@)

_CRR_BIN="@CRR_BIN@"

# [lesson: env leakage] Scrub inherited control vars so a revived tmux
# session's environment never leaks into an ordinary shell.
for _crr_v in ${(k)parameters[(I)CRR_CTRL_*]}; do unset "$_crr_v"; done
unset _crr_v

# [lesson: PATH poisoning] Absolute path only; a missing binary is a silent
# no-op, never an error line into the prompt.
_crr() {
  [[ -x "$_CRR_BIN" ]] || return 0
  "$_CRR_BIN" "$@" 2>/dev/null
}

# Args to add to every claude launch so a session is always reachable
# from Claude Code's mobile Remote Control (`--remote-control` is
# per-invocation, not sticky — every launch has to ask fresh, not just
# fresh ones). Printed one token per line by `crr`, so an unquoted
# expansion here splits into exactly the right words; the token itself is
# sanitized to letters/digits/dash/underscore (crr.core.reviver), so
# splitting it unquoted never risks pathname expansion either. Silent
# no-op (empty expansion) when disabled, untracked, or crr is missing —
# same "never break a launch" contract as `_crr` itself.
#
# Placed BEFORE "$@" at every call site, never after: "$@" can be a bare
# prompt (`claude "fix the bug"`), and claude's parser mode for flags
# after a positional argument is undocumented — putting our flag first
# keeps it unambiguously a flag regardless. Safe under THE HAZARD too: the
# name is always explicit, so `--remote-control proj --resume abc123`
# reads `proj` as the name and leaves `--resume` alone.
_crr_rc_args() {
  _crr remote-control-args --pid "$$"
}

_crr_host() {
  if [[ -n "$TMUX" ]]; then print -n tmux
  elif [[ -n "$SSH_TTY$SSH_CONNECTION" ]]; then print -n ssh
  else print -n tab
  fi
}

# Register this shell at start.
_crr register --pid "$$" --cwd "$PWD" --shell zsh --host "$(_crr_host)" >/dev/null

# Phase-3 restore prompt: once per boot, offer to re-home rescued sessions.
if [[ -o interactive && -x "$_CRR_BIN" ]]; then
    "$_CRR_BIN" rescue-check 2>/dev/null
fi

# zsh has native preexec / zshexit hooks — no DEBUG-trap gymnastics.
_crr_preexec() { _crr last-cmd --pid "$$" --cmd "$1" --cwd "$PWD" >/dev/null; }
_crr_deregister() { _crr deregister --pid "$$" >/dev/null; }

autoload -Uz add-zsh-hook 2>/dev/null
if (( $+functions[add-zsh-hook] )); then
  add-zsh-hook preexec _crr_preexec
  add-zsh-hook zshexit _crr_deregister
else
  preexec_functions+=(_crr_preexec)
  zshexit_functions+=(_crr_deregister)
fi

# claude() wrapper: inject + journal a --session-id on fresh launches
# (sid_source=injected); on resume/continue, journal the resumed session
# (guessed/verified sid) so it is revivable, args untouched. After each
# exit the repair loop consumes the relaunch/close flag: kick → silent
# --resume, close → deregister + exit this shell, bare crash → offer
# ([Y/n]; yes/timeout/no-tty resume, ≤2 attempts), clean exit → prompt.
claude() {
  # Offer timeout (seconds) for the crash prompt; overridable, never inline.
  : "${_CRR_OFFER_TIMEOUT:=30}"
  # Give-up cap for consecutive crash resumes; overridable, never inline.
  : "${_CRR_MAX_RESUMES:=2}"
  # [lesson: flag files] A stale flag from a prior action must never act on
  # this launch.
  _crr repair-check --pid "$$" --clear >/dev/null

  # Element-wise flag detection: match whole arguments, never a substring
  # of prompt text (a prompt like "explain -r" is a fresh launch).
  local _arg _resuming=
  for _arg in "$@"; do
    case "$_arg" in
      -r|--resume|--resume=*|-c|--continue|--session-id|--session-id=*)
        _resuming=1; break ;;
    esac
  done
  # The conversation the repair loop resumes: injected sid on a fresh
  # launch, explicit sid on a resume, sid of each consumed relaunch flag.
  local _cur_sid=
  if [ -n "$_resuming" ]; then
    # Extract an explicit resume sid if given (-r <sid>, --resume <sid|=sid>,
    # --session-id <sid|=sid>); a '-'-prefixed value is another flag, not the
    # sid, so it is left empty and the sid is guessed from the newest transcript.
    local _sid= _want=
    for _arg in "$@"; do
      if [ -n "$_want" ]; then
        case "$_arg" in -*) ;; *) _sid="$_arg" ;; esac
        _want=
        continue
      fi
      case "$_arg" in
        -r|--resume|--session-id) _want=1 ;;
        --resume=*) _sid="${_arg#--resume=}" ;;
        --session-id=*) _sid="${_arg#--session-id=}" ;;
      esac
    done
    if [ -n "$_sid" ]; then
      # [#48] Refuse to become a SECOND claude on a conversation that
      # already has one. Non-zero means the user chose to abort (or
      # there was no tty to ask) — do not launch.
      if ! _crr conflict-check --sid "$_sid"; then
        return 1
      fi
      _crr claude-resume --pid "$$" --cwd "$PWD" --session-id "$_sid" >/dev/null
      _cur_sid="$_sid"
    else
      _crr claude-resume --pid "$$" --cwd "$PWD" >/dev/null
    fi
    command claude $(_crr_rc_args) "$@"
  else
    local _crr_sid
    _crr_sid="$(_crr claude-launch --pid "$$")"
    if [ -n "$_crr_sid" ]; then
      _cur_sid="$_crr_sid"
      command claude --session-id "$_crr_sid" $(_crr_rc_args) "$@"
    else
      command claude $(_crr_rc_args) "$@"
    fi
  fi
  local _code=$?

  local _crashes=0 _flagline _kind _fsid _ans
  while [ -x "$_CRR_BIN" ]; do
    # Read, then clear: two calls by design (re-arm window accepted).
    _flagline="$(_crr repair-check --pid "$$")"
    _crr repair-check --pid "$$" --clear >/dev/null
    _kind= _fsid=
    [ -n "$_flagline" ] && read -r _kind _fsid <<< "$_flagline"
    # A bare "relaunch" (no sid) fails the -n test and safely falls
    # through to the absent branches below.
    if [ "$_kind" = relaunch ] && [ -n "$_fsid" ]; then
      _cur_sid="$_fsid"
      _crashes=0
      command claude --resume "$_fsid" $(_crr_rc_args)
      _code=$?
      continue
    fi
    if [ "$_kind" = close ]; then
      _crr claude-exit --pid "$$"
      exit
    fi
    # Unknown kind or no flag: branch on how claude exited.
    [ "$_code" -eq 0 ] && break
    [ "$_crashes" -ge "$_CRR_MAX_RESUMES" ] && break
    _ans=
    if [ -t 0 ]; then
      printf 'crr: claude exited unexpectedly (%s). Resume this conversation? [Y/n] ' "$_code" >&2
      IFS= read -r -t "$_CRR_OFFER_TIMEOUT" _ans || _ans=
    fi
    case "$_ans" in n|N|no|No|NO) break ;; esac
    _crashes=$((_crashes + 1))
    if [ -n "$_cur_sid" ]; then
      command claude --resume "$_cur_sid" $(_crr_rc_args)
      _code=$?
    else
      _crr claude-resume --pid "$$" --cwd "$PWD" >/dev/null
      command claude --continue $(_crr_rc_args)
      _code=$?
    fi
  done
  _crr claude-exit --pid "$$"
}
