# crr fish shim — source this from ~/.config/fish/config.fish.  Generated by
# `crr shim fish`, which bakes the absolute crr path into the set below.
# Dependency-free; safe to source even when crr is absent.
# generated by crr @CRR_VERSION@ (config-defaults v@CRR_DEFAULTS_V@)

set -g _CRR_BIN "@CRR_BIN@"

# [lesson: env leakage] Scrub inherited control vars so a revived tmux
# session's environment never leaks into an ordinary shell.
for _crr_v in (set --names | string match 'CRR_CTRL_*')
    set -e $_crr_v
end

# [lesson: PATH poisoning] Absolute path only; a missing binary is a silent
# no-op, never an error line into the prompt.
function _crr
    test -x "$_CRR_BIN"; or return 0
    "$_CRR_BIN" $argv 2>/dev/null
end

# Args to add to every claude launch so a session is always reachable
# from Claude Code's mobile Remote Control (`--remote-control` is
# per-invocation, not sticky — every launch has to ask fresh, not just
# fresh ones). Printed one token per line by `crr`, so an unquoted fish
# command substitution here splits into exactly the right list elements;
# the token itself is sanitized to letters/digits/dash/underscore
# (crr.core.reviver). Silent no-op (empty list) when disabled, untracked,
# or crr is missing — same "never break a launch" contract as `_crr` itself.
#
# Placed BEFORE $argv at every call site, never after: $argv can be a bare
# prompt (`claude "fix the bug"`), and claude's parser mode for flags
# after a positional argument is undocumented — putting our flag first
# keeps it unambiguously a flag regardless. Safe under THE HAZARD too: the
# name is always explicit, so `--remote-control proj --resume abc123`
# reads `proj` as the name and leaves `--resume` alone.
function _crr_rc_args
    _crr remote-control-args --pid $fish_pid
end

function _crr_host
    if set -q TMUX
        echo -n tmux
    else if set -q SSH_TTY; or set -q SSH_CONNECTION
        echo -n ssh
    else
        echo -n tab
    end
end

# Register this shell at start.
_crr register --pid $fish_pid --cwd $PWD --shell fish --host (_crr_host) >/dev/null

# Phase-3 restore prompt: once per boot, offer to re-home rescued sessions.
# stdout stays attached (the [Y/n] prompt); stderr never leaks into the prompt.
if status is-interactive; and test -x "$_CRR_BIN"
    "$_CRR_BIN" rescue-check 2>/dev/null
end

# fish's native event hooks — preexec before each command, exit on teardown.
function _crr_preexec --on-event fish_preexec
    _crr last-cmd --pid $fish_pid --cmd "$argv" --cwd $PWD >/dev/null
end

function _crr_deregister --on-event fish_exit
    _crr deregister --pid $fish_pid >/dev/null
end

# claude() wrapper: inject + journal a --session-id on fresh launches
# (sid_source=injected); on resume/continue, journal the resumed session
# (guessed/verified sid) so it is revivable, args untouched. After each
# exit the repair loop consumes the relaunch/close flag: kick → silent
# --resume, close → deregister + exit this shell, bare crash → offer
# ([Y/n]; yes/no-tty resume, ≤2 attempts), clean exit → back to prompt.
function claude
    # Give-up cap for consecutive crash resumes; overridable, never inline.
    # fish has no timeout var (blocking read), so this is the only named
    # constant here.
    set -q _CRR_MAX_RESUMES; or set -l _CRR_MAX_RESUMES 2
    # [lesson: flag files] A stale flag from a prior action must never act
    # on this launch.
    _crr repair-check --pid $fish_pid --clear >/dev/null

    # Element-wise flag detection: whole arguments only, never a substring
    # of prompt text (a prompt like "explain -r" is a fresh launch).
    # `--continue` is tracked separately from the rest: it is the one
    # resume shape that names no conversation yet still lands on a
    # specific one (#68). No early break — an argv carrying both -c and an
    # explicit --resume sid must still be seen as having the sid.
    set -l _resuming 0
    set -l _continuing 0
    set -l _skip_perms 0
    for _arg in $argv
        switch $_arg
            case -c --continue
                set _resuming 1
                set _continuing 1
            case -r --resume '--resume=*' --session-id '--session-id=*'
                set _resuming 1
            case --dangerously-skip-permissions
                set _skip_perms 1
        end
    end
    set -l _crr_sp_args
    set -l _dsp_args
    if test $_skip_perms -eq 1
        set _crr_sp_args --skip-permissions
        set _dsp_args --dangerously-skip-permissions
    end
    # The conversation the repair loop resumes: injected sid on a fresh
    # launch, explicit sid on a resume, sid of each consumed relaunch flag.
    set -l _cur_sid ""
    if test $_resuming -eq 1
        # Extract an explicit resume sid if given (-r <sid>, --resume <sid|=sid>,
        # --session-id <sid|=sid>); a '-'-prefixed value is another flag, not the
        # sid, so it is left empty and the sid is guessed from the newest transcript.
        set -l _sid ""
        set -l _want 0
        for _arg in $argv
            if test $_want -eq 1
                switch $_arg
                    case '-*'
                    case '*'
                        set _sid $_arg
                end
                set _want 0
                continue
            end
            switch $_arg
                case -r --resume --session-id
                    set _want 1
                case '--resume=*'
                    set _sid (string replace -- '--resume=' '' $_arg)
                case '--session-id=*'
                    set _sid (string replace -- '--session-id=' '' $_arg)
            end
        end
        if test -n "$_sid"
            # [#48] Refuse to become a SECOND claude on a conversation
            # that already has one. Non-zero means the user chose to
            # abort (or there was no tty to ask) — do not launch.
            if not _crr conflict-check --sid $_sid
                return 1
            end
            _crr claude-resume --pid $fish_pid --cwd $PWD --session-id $_sid $_crr_sp_args >/dev/null
            set _cur_sid $_sid
        else
            # [#68] `--continue` hands crr no sid, but the conversation it
            # will resume is predictable — the newest transcript here —
            # and crr already uses that same prediction to journal this
            # launch below. Check it BEFORE launching, so the duplicate is
            # prevented rather than merely reported by the dashboard card.
            # Only for -c/--continue: a bare `--resume` opens claude's
            # picker, where the user may choose any conversation, and
            # forcing a kill choice about the newest would be wrong.
            if test $_continuing -eq 1
                _crr conflict-check --cwd $PWD
                set -l _cc $status
                # 2 means this crr does not understand --cwd — an older
                # deploy than this shim. Unanswered is not a refusal: the
                # shim's standing contract is that crr can never break a
                # launch, and the conflict card still catches it after the
                # fact. Every other non-zero IS the refusal.
                if test $_cc -ne 0; and test $_cc -ne 2
                    return 1
                end
            end
            _crr claude-resume --pid $fish_pid --cwd $PWD $_crr_sp_args >/dev/null
        end
        command claude (_crr_rc_args) $argv
    else
        set -l _crr_sid (_crr claude-launch --pid $fish_pid $_crr_sp_args)
        if test -n "$_crr_sid"
            set _cur_sid $_crr_sid
            command claude --session-id $_crr_sid (_crr_rc_args) $argv
        else
            command claude (_crr_rc_args) $argv
        end
    end
    set -l _code $status

    # Clean exit (/exit, code 0): clear the journal claude field NOW, before
    # the repair-check round-trips below. Those are several sequential
    # `crr` process startups, and for their whole duration the entry still
    # carries claude — so a tab-close in that window (SIGHUP -> fish_exit ->
    # `crr deregister`) archives a session the user already ended cleanly as
    # a revivable "shell-exited" one, and the next new tab resurrects it
    # [/exit revival 2026-08-24]. Clearing first shrinks that race to the gap between claude
    # returning and this one call. Crash paths (code != 0) deliberately keep
    # the field set so a genuine mid-session close still revives.
    if test $_code -eq 0
        _crr claude-exit --pid $fish_pid
    end

    set -l _crashes 0
    while test -x "$_CRR_BIN"
        # Command substitution splits on newlines only — split the single
        # flag line on spaces ourselves. Absent = no output = empty list.
        # Read, then clear: two calls by design (re-arm window accepted).
        set -l _flag (_crr repair-check --pid $fish_pid | string split ' ')
        _crr repair-check --pid $fish_pid --clear >/dev/null
        # Quoted out-of-range index expands empty, so a bare "relaunch"
        # (no sid) safely falls through to the absent branches below.
        if test "$_flag[1]" = relaunch; and test -n "$_flag[2]"
            set _cur_sid $_flag[2]
            set _crashes 0
            command claude --resume $_flag[2] $_dsp_args (_crr_rc_args)
            set _code $status
            continue
        end
        if test "$_flag[1]" = close
            _crr claude-exit --pid $fish_pid
            exit
        end
        # Unknown kind or no flag: branch on how claude exited.
        if test $_code -eq 0
            break
        end
        if test $_crashes -ge $_CRR_MAX_RESUMES
            break
        end
        set -l _ans ""
        if test -t 0
            # Newline-terminated: fish's read repaints its own `read>` prompt
            # on the current line, which would erase a same-line question
            # (found in the live smoke test; bash/zsh read doesn't repaint).
            printf 'crr: claude exited unexpectedly (%s). Resume this conversation? [Y/n]\n' $_code >&2
            # fish has no timed read — block; the no-tty guard above covers
            # the unattended case.
            read _ans
        end
        switch $_ans
            case n N no No NO
                break
        end
        set _crashes (math $_crashes + 1)
        if test -n "$_cur_sid"
            command claude --resume $_cur_sid $_dsp_args (_crr_rc_args)
        else
            # [#68] Deliberately NOT conflict-checked, unlike the launch
            # path above: this is crash recovery resuming the conversation
            # that just died in THIS shell. The only agent it could
            # collide with is the one that is already gone, and prompting
            # here would ask the user to kill their own dead session.
            _crr claude-resume --pid $fish_pid --cwd $PWD $_crr_sp_args >/dev/null
            command claude --continue $_dsp_args (_crr_rc_args)
        end
        set _code $status
    end
    _crr claude-exit --pid $fish_pid
end
