# crr zsh shim — source this from ~/.zshrc.  Generated by `crr shim zsh`,
# which bakes the absolute crr path into the assignment below.
# Dependency-free; safe to source even when crr is absent.

_CRR_BIN="@CRR_BIN@"

# [lesson: env leakage] Scrub inherited control vars so a revived tmux
# session's environment never leaks into an ordinary shell.
for _crr_v in ${(k)parameters[(I)CRR_CTRL_*]}; do unset "$_crr_v"; done
unset _crr_v

# [lesson: PATH poisoning] Absolute path only; a missing binary is a silent
# no-op, never an error line into the prompt.
_crr() {
  [[ -x "$_CRR_BIN" ]] || return 0
  "$_CRR_BIN" "$@" 2>/dev/null
}

_crr_host() {
  if [[ -n "$TMUX" ]]; then print -n tmux
  elif [[ -n "$SSH_TTY$SSH_CONNECTION" ]]; then print -n ssh
  else print -n tab
  fi
}

# Register this shell at start.
_crr register --pid "$$" --cwd "$PWD" --shell zsh --host "$(_crr_host)" >/dev/null

# zsh has native preexec / zshexit hooks — no DEBUG-trap gymnastics.
_crr_preexec() { _crr last-cmd --pid "$$" --cmd "$1" --cwd "$PWD" >/dev/null; }
_crr_deregister() { _crr deregister --pid "$$" >/dev/null; }

autoload -Uz add-zsh-hook 2>/dev/null
if (( $+functions[add-zsh-hook] )); then
  add-zsh-hook preexec _crr_preexec
  add-zsh-hook zshexit _crr_deregister
else
  preexec_functions+=(_crr_preexec)
  zshexit_functions+=(_crr_deregister)
fi
