# crr bash shim — source this from ~/.bashrc.  Generated by `crr shim bash`,
# which bakes the absolute crr path into the assignment below.
# Dependency-free; safe to source even when crr is absent.

_CRR_BIN="@CRR_BIN@"

# [lesson: env leakage] A shell spawned from a revived tmux session inherits
# the revival environment.  Scrub inherited control vars so they never leak
# into an ordinary shell (config vars like _CRR_BIN are set below, not here).
for _crr_v in ${!CRR_CTRL_@}; do unset "$_crr_v"; done
unset _crr_v

# [lesson: PATH poisoning] Absolute path only, never a PATH lookup; and a
# missing/again-broken binary must be a silent no-op, never an error line.
_crr() {
  [ -x "$_CRR_BIN" ] || return 0
  "$_CRR_BIN" "$@" 2>/dev/null
}

_crr_host() {
  if [ -n "$TMUX" ]; then printf tmux
  elif [ -n "$SSH_TTY" ] || [ -n "$SSH_CONNECTION" ]; then printf ssh
  else printf tab
  fi
}

# Register this shell at start.
_crr register --pid "$$" --cwd "$PWD" --shell bash --host "$(_crr_host)" >/dev/null

# preexec approximation: record the command about to run, plus current cwd.
# Skip the shim's own helpers and completion so we don't journal noise.
_crr_preexec() {
  [ -n "$COMP_LINE" ] && return
  case "$BASH_COMMAND" in _crr*|"$PROMPT_COMMAND") return ;; esac
  _crr last-cmd --pid "$$" --cmd "$BASH_COMMAND" --cwd "$PWD" >/dev/null
}
trap '_crr_preexec' DEBUG

# Deregister on shell exit.
_crr_deregister() { _crr deregister --pid "$$" >/dev/null; }
trap '_crr_deregister' EXIT

# claude() wrapper: on a fresh launch, inject a --session-id so the session
# is identifiable and journal it (sid_source=injected). On resume/continue,
# journal the resumed session too (guessed/verified sid) so it is revivable —
# claude runs with the user's args untouched. On clean exit, clear the claude
# field; a crash skips that, leaving the sid for the reviver.
claude() {
  # Element-wise flag detection: match whole arguments, never a substring
  # of prompt text (a prompt like "explain -r" is a fresh launch).
  local _arg _resuming=
  for _arg in "$@"; do
    case "$_arg" in
      -r|--resume|--resume=*|-c|--continue|--session-id|--session-id=*)
        _resuming=1; break ;;
    esac
  done
  if [ -n "$_resuming" ]; then
    # Extract an explicit resume sid if one was given (-r <sid>,
    # --resume <sid|=sid>, --session-id <sid|=sid>); a value that starts with
    # '-' is another flag, not the sid (`claude -r --model x`), so it is left
    # empty and the sid is guessed from the newest transcript instead.
    local _sid= _want=
    for _arg in "$@"; do
      if [ -n "$_want" ]; then
        case "$_arg" in -*) ;; *) _sid="$_arg" ;; esac
        _want=
        continue
      fi
      case "$_arg" in
        -r|--resume|--session-id) _want=1 ;;
        --resume=*) _sid="${_arg#--resume=}" ;;
        --session-id=*) _sid="${_arg#--session-id=}" ;;
      esac
    done
    if [ -n "$_sid" ]; then
      _crr claude-resume --pid "$$" --cwd "$PWD" --session-id "$_sid" >/dev/null
    else
      _crr claude-resume --pid "$$" --cwd "$PWD" >/dev/null
    fi
    command claude "$@"
  else
    local _crr_sid
    _crr_sid="$(_crr claude-launch --pid "$$")"
    if [ -n "$_crr_sid" ]; then
      command claude --session-id "$_crr_sid" "$@"
    else
      command claude "$@"
    fi
  fi
  _crr claude-exit --pid "$$"
}
