# crr bash shim — source this from ~/.bashrc.  Generated by `crr shim bash`,
# which bakes the absolute crr path into the assignment below.
# Dependency-free; safe to source even when crr is absent.
# generated by crr @CRR_VERSION@ (config-defaults v@CRR_DEFAULTS_V@)

_CRR_BIN="@CRR_BIN@"

# [lesson: env leakage] A shell spawned from a revived tmux session inherits
# the revival environment.  Scrub inherited control vars so they never leak
# into an ordinary shell (config vars like _CRR_BIN are set below, not here).
for _crr_v in ${!CRR_CTRL_@}; do unset "$_crr_v"; done
unset _crr_v

# [lesson: PATH poisoning] Absolute path only, never a PATH lookup; and a
# missing/again-broken binary must be a silent no-op, never an error line.
_crr() {
  [ -x "$_CRR_BIN" ] || return 0
  "$_CRR_BIN" "$@" 2>/dev/null
}

# Args to add to every claude launch so a session is always reachable
# from Claude Code's mobile Remote Control (`--remote-control` is
# per-invocation, not sticky — every launch has to ask fresh, not just
# fresh ones). Printed one token per line by `crr`, so an unquoted
# expansion here splits into exactly the right words; the token itself is
# sanitized to letters/digits/dash/underscore (crr.core.reviver), so
# splitting it unquoted never risks pathname expansion either. Silent
# no-op (empty expansion) when disabled, untracked, or crr is missing —
# same "never break a launch" contract as `_crr` itself.
#
# Placed BEFORE "$@" at every call site, never after: "$@" can be a bare
# prompt (`claude "fix the bug"`), and claude's parser mode for flags
# after a positional argument is undocumented — putting our flag first
# keeps it unambiguously a flag regardless. Safe under THE HAZARD too: the
# name is always explicit, so `--remote-control proj --resume abc123`
# reads `proj` as the name and leaves `--resume` alone.
_crr_rc_args() {
  _crr remote-control-args --pid "$$"
}

_crr_host() {
  if [ -n "$TMUX" ]; then printf tmux
  elif [ -n "$SSH_TTY" ] || [ -n "$SSH_CONNECTION" ]; then printf ssh
  else printf tab
  fi
}

# Register this shell at start.
_crr register --pid "$$" --cwd "$PWD" --shell bash --host "$(_crr_host)" >/dev/null

# Phase-3 restore prompt: once per boot, offer to re-home rescued sessions.
if [[ $- == *i* && -x "$_CRR_BIN" ]]; then
    "$_CRR_BIN" rescue-check 2>/dev/null
fi

# preexec approximation: record the command about to run, plus current cwd.
# Skip the shim's own helpers and completion so we don't journal noise.
_crr_preexec() {
  [ -n "$COMP_LINE" ] && return
  case "$BASH_COMMAND" in _crr*|"$PROMPT_COMMAND") return ;; esac
  _crr last-cmd --pid "$$" --cmd "$BASH_COMMAND" --cwd "$PWD" >/dev/null
}
trap '_crr_preexec' DEBUG

# Deregister on shell exit.
_crr_deregister() { _crr deregister --pid "$$" >/dev/null; }
trap '_crr_deregister' EXIT

# claude() wrapper: on a fresh launch, inject a --session-id so the session
# is identifiable and journal it (sid_source=injected). On resume/continue,
# journal the resumed session too (guessed/verified sid) so it is revivable.
# After each exit the repair loop consumes the relaunch/close flag: kick →
# silent --resume, close → deregister + exit this shell, bare crash → offer
# ([Y/n]; yes/timeout/no-tty resume, ≤2 attempts), clean exit → prompt.
claude() {
  # Offer timeout (seconds) for the crash prompt; overridable, never inline.
  : "${_CRR_OFFER_TIMEOUT:=30}"
  # Give-up cap for consecutive crash resumes; overridable, never inline.
  : "${_CRR_MAX_RESUMES:=2}"
  # [lesson: flag files] A stale flag from a prior action must never act on
  # this launch.
  _crr repair-check --pid "$$" --clear >/dev/null

  # Element-wise flag detection: match whole arguments, never a substring
  # of prompt text (a prompt like "explain -r" is a fresh launch).
  # `--continue` is tracked separately from the rest: it is the one resume
  # shape that names no conversation yet still lands on a specific one
  # (#68). No early break — an argv carrying both -c and an explicit
  # --resume sid must still be seen as having the sid.
  local _arg _resuming= _continuing=
  for _arg in "$@"; do
    case "$_arg" in
      -c|--continue) _resuming=1; _continuing=1 ;;
      -r|--resume|--resume=*|--session-id|--session-id=*) _resuming=1 ;;
    esac
  done
  # The conversation the repair loop resumes: injected sid on a fresh
  # launch, explicit sid on a resume, sid of each consumed relaunch flag.
  local _cur_sid= _cc=
  if [ -n "$_resuming" ]; then
    # Extract an explicit resume sid if one was given (-r <sid>,
    # --resume <sid|=sid>, --session-id <sid|=sid>); a value that starts with
    # '-' is another flag, not the sid (`claude -r --model x`), so it is left
    # empty and the sid is guessed from the newest transcript instead.
    local _sid= _want=
    for _arg in "$@"; do
      if [ -n "$_want" ]; then
        case "$_arg" in -*) ;; *) _sid="$_arg" ;; esac
        _want=
        continue
      fi
      case "$_arg" in
        -r|--resume|--session-id) _want=1 ;;
        --resume=*) _sid="${_arg#--resume=}" ;;
        --session-id=*) _sid="${_arg#--session-id=}" ;;
      esac
    done
    if [ -n "$_sid" ]; then
      # [#48] Refuse to become a SECOND claude on a conversation that
      # already has one. Non-zero means the user chose to abort (or
      # there was no tty to ask) — do not launch.
      if ! _crr conflict-check --sid "$_sid"; then
        return 1
      fi
      _crr claude-resume --pid "$$" --cwd "$PWD" --session-id "$_sid" >/dev/null
      _cur_sid="$_sid"
    else
      # [#68] `--continue` hands crr no sid, but the conversation it will
      # resume is predictable — the newest transcript here — and crr
      # already uses that same prediction to journal this launch below.
      # Check it BEFORE launching, so the duplicate is prevented rather
      # than merely reported by the dashboard card. Only for
      # -c/--continue: a bare `--resume` opens claude's picker, where the
      # user may choose any conversation, and forcing a kill choice about
      # the newest would be wrong.
      if [ -n "$_continuing" ]; then
        _crr conflict-check --cwd "$PWD"
        _cc=$?
        # 2 means this crr does not understand --cwd — an older deploy
        # than this shim. Unanswered is not a refusal: the shim's standing
        # contract is that crr can never break a launch, and the conflict
        # card still catches it after the fact. Every other non-zero IS
        # the refusal.
        if [ "$_cc" -ne 0 ] && [ "$_cc" -ne 2 ]; then
          return 1
        fi
      fi
      _crr claude-resume --pid "$$" --cwd "$PWD" >/dev/null
    fi
    command claude $(_crr_rc_args) "$@"
  else
    local _crr_sid
    _crr_sid="$(_crr claude-launch --pid "$$")"
    if [ -n "$_crr_sid" ]; then
      _cur_sid="$_crr_sid"
      command claude --session-id "$_crr_sid" $(_crr_rc_args) "$@"
    else
      command claude $(_crr_rc_args) "$@"
    fi
  fi
  local _code=$?

  local _crashes=0 _flagline _kind _fsid _ans
  while [ -x "$_CRR_BIN" ]; do
    # Read, then clear: two calls by design (re-arm window accepted).
    _flagline="$(_crr repair-check --pid "$$")"
    _crr repair-check --pid "$$" --clear >/dev/null
    _kind= _fsid=
    [ -n "$_flagline" ] && read -r _kind _fsid <<< "$_flagline"
    # A bare "relaunch" (no sid) fails the -n test and safely falls
    # through to the absent branches below.
    if [ "$_kind" = relaunch ] && [ -n "$_fsid" ]; then
      _cur_sid="$_fsid"
      _crashes=0
      command claude --resume "$_fsid" $(_crr_rc_args)
      _code=$?
      continue
    fi
    if [ "$_kind" = close ]; then
      _crr claude-exit --pid "$$"
      exit
    fi
    # Unknown kind or no flag: branch on how claude exited.
    [ "$_code" -eq 0 ] && break
    [ "$_crashes" -ge "$_CRR_MAX_RESUMES" ] && break
    _ans=
    if [ -t 0 ]; then
      printf 'crr: claude exited unexpectedly (%s). Resume this conversation? [Y/n] ' "$_code" >&2
      IFS= read -r -t "$_CRR_OFFER_TIMEOUT" _ans || _ans=
    fi
    case "$_ans" in n|N|no|No|NO) break ;; esac
    _crashes=$((_crashes + 1))
    if [ -n "$_cur_sid" ]; then
      command claude --resume "$_cur_sid" $(_crr_rc_args)
      _code=$?
    else
      # [#68] Deliberately NOT conflict-checked, unlike the launch path
      # above: this is crash recovery resuming the conversation that just
      # died in THIS shell. The only agent it could collide with is the
      # one that is already gone, and prompting here would ask the user to
      # kill their own dead session.
      _crr claude-resume --pid "$$" --cwd "$PWD" >/dev/null
      command claude --continue $(_crr_rc_args)
      _code=$?
    fi
  done
  _crr claude-exit --pid "$$"
}
